install:
- npm install
- ./node_modules/.bin/electron-rebuild
language: node_js
node_js:
- lts/*
- "9"
- "10"
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libgphoto2-6
    - libgphoto2-dev
    - libgphoto2-port10
